import React, { useState } from "react";

/*
controlled form

1. state
2. values
3. handleChange
*/
export default function ListingForm({addItem}) {
    const initialForm = {
        //let json-server handle id
        description: '',
        image: '',
        location: '',
    }

    const [form, setForm] = useState(initialForm)

    const handleChange = (e) => {
        setForm({
            ...form,
            [e.target.name]: e.target.value
        })
    }

    const handleSubmit = (e) => {
        e.preventDefault()
        fetch(`http://localhost:6001/listings`, {
            method: 'POST',
            headers: {'content-type': 'application/json'},
            body: JSON.stringify(form)
        })
        .then(res => {
            if(res.ok){
                return res.json()
            } else {
                console.error('oops')
            }
        })
        .then(data => {
            console.log(data)
            //pass up data NOT form...data has id generated by json-server, form does not
            addItem(data)
            setForm(initialForm)
        })
    }

	return (
		<form onSubmit={(e) => handleSubmit(e)}>
			<input type="text" onChange={(e) => handleChange(e)} value={form.description} name="description" placeholder="name" />
			<input type="text" onChange={(e) => handleChange(e)} value={form.image} name="image" placeholder="image" />
			<input type="text" onChange={(e) => handleChange(e)} value={form.location} name="location" placeholder="location" />
			<input type="submit" text="submit" />
		</form>
	);
}
